# NUMPY ARRAY

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [1,2,3], [1,2,3]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
z = np.zeros((5,5))

In [12]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
 np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(4)

array([0.85549675, 0.02433195, 0.79218424, 0.44211939])

In [19]:
np.random.rand(4,5)

array([[0.98304604, 0.30693778, 0.53715653, 0.32861561, 0.34351029],
       [0.84318845, 0.6717265 , 0.82783036, 0.8623101 , 0.21805124],
       [0.78511051, 0.91793913, 0.49683489, 0.37840455, 0.0450372 ],
       [0.10946505, 0.59799339, 0.78937139, 0.18421505, 0.43208498]])

In [20]:
np.random.randn(5,6)

array([[-0.42050649, -0.19027146, -1.72851079, -0.4144546 , -0.99266494,
        -0.07883811],
       [-0.61279439, -0.78271498, -0.9733656 ,  1.86408479, -0.26842588,
        -0.39484158],
       [ 0.89038239, -0.09676504,  0.82136218, -0.56014195, -0.83295856,
        -1.06387547],
       [-0.28005251, -0.76708634,  1.22370164,  0.53587279,  1.83369211,
         0.04723041],
       [-0.27489676, -0.62879534, -1.16400357, -1.75652729,  0.84386248,
         0.87968935]])

In [21]:
np.random.randn(3)

array([-0.72878024,  0.34431755, -1.23852018])

In [22]:
np.random.randint(10)

1

In [23]:
np.random.randint(1,10,5)

array([4, 1, 8, 5, 2])

In [24]:
ranarr = np.arange(25)

In [25]:
ranarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr1 = (1,20,3)

In [27]:
ranarr1

(1, 20, 3)

In [28]:
 ranarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

24

In [30]:
ranarr.min()

0

In [31]:
ranarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.shape

(3,)

In [34]:
arr.dtype

dtype('int32')

In [35]:
from numpy.random import randn

In [36]:
randn(1,10,2)

array([[[-2.27071951,  1.60827466],
        [ 0.48770067,  0.8176408 ],
        [-0.89665136, -0.28816205],
        [-0.76347383, -0.90858975],
        [ 1.1686658 ,  0.46565645],
        [ 0.71517977,  0.04564022],
        [ 0.94571534, -0.08045342],
        [-1.75893611, -1.22732671],
        [ 0.81092915,  0.37373077],
        [ 0.1208438 , -1.34884443]]])

In [37]:
from numpy.random import randint

In [38]:
randint(3,18)

8

In [39]:
import numpy as np

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [45]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [46]:
arr / arr

C:\Users\user\AppData\Local\Temp\ipykernel_17508\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [47]:
1 /arr

C:\Users\user\AppData\Local\Temp\ipykernel_17508\4127448963.py:1: RuntimeWarning: divide by zero encountered in divide
  1 /arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [48]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [51]:
np.max(arr)

10

In [52]:
np.min(arr)

0

In [53]:
arr.min()

0

In [54]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [55]:
np.log(arr)

C:\Users\user\AppData\Local\Temp\ipykernel_17508\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [56]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [57]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [58]:
x = [[1,2,3,4], [5,6,7,8] ,[2,4,6,8]]

In [59]:
X = np.array(x)

In [60]:
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [61]:
Y = np.ones((3,4))

In [62]:
Y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
Z = X + Y

In [64]:
Z

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.],
       [3., 5., 7., 9.]])

In [65]:
arr = np.arange(0,11)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr[2:6] = 100

In [70]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [71]:
arr[5]

100

In [72]:
arr[::-1]

array([ 10,   9,   8,   7,   6, 100, 100, 100, 100,   1,   0])

In [73]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [74]:
arr[::-1][5]

100

In [75]:
brd_arr = arr[2:] 

In [76]:
brd_arr

array([100, 100, 100, 100,   6,   7,   8,   9,  10])

In [77]:
y = brd_arr.copy() 

In [78]:
y

array([100, 100, 100, 100,   6,   7,   8,   9,  10])

In [79]:
brd_arr

array([100, 100, 100, 100,   6,   7,   8,   9,  10])

In [80]:
Z[2][3]

9.0

In [81]:
Z[2,3]

9.0

In [82]:
Z[0,1]

3.0

In [83]:
Z[0,1] = 5

In [84]:
Z

array([[2., 5., 4., 5.],
       [6., 7., 8., 9.],
       [3., 5., 7., 9.]])

In [85]:
Z[:1,2:]

array([[4., 5.]])

In [86]:
x = [[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]

In [87]:
p = np.array(x)

In [88]:
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
p[: :, 1 :]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [90]:
p[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [91]:
p[1:3,:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [92]:
p[2:,1:]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [93]:
arr < 5

array([ True,  True, False, False, False, False, False, False, False,
       False, False])

In [94]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [95]:
y = np.arange(10,21)

In [96]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [97]:
Y = y >= 15

In [98]:
arr[Y]

array([100,   6,   7,   8,   9,  10])

In [99]:
arr[arr>4]

array([100, 100, 100, 100,   6,   7,   8,   9,  10])

In [100]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [101]:
y[y>16]

array([17, 18, 19, 20])

In [102]:
p[p>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [103]:
 z = np.arange(50,100).reshape(5,10)

In [104]:
z

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
z[1:4,2:8]

array([[62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87]])

In [106]:
z[::-1][1:4,2:8]

array([[82, 83, 84, 85, 86, 87],
       [72, 73, 74, 75, 76, 77],
       [62, 63, 64, 65, 66, 67]])

In [107]:
p =np.random.rand

In [108]:
import numpy as np

In [109]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [110]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
np.max(arr)

12

In [113]:
arr.min()

1

In [114]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
arr1 = np.arange(0,10) 

In [117]:
brd = arr1[::] = 5

In [118]:
arr1

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [119]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [120]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [121]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [122]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.random.random(1)

array([0.95302749])

In [125]:
np.random.randn(25)

array([-0.44811231,  0.08624875, -0.75419329, -1.71033518,  0.94966463,
        0.07912014, -0.66255569,  0.53441941, -0.51356012,  0.21389042,
       -1.24008466, -1.42180705, -0.46254554,  1.59281993,  0.62097685,
        1.3819351 , -0.47033433, -0.20277627,  0.55379342, -1.66810142,
        0.58569991,  0.65906102,  0.2966691 ,  0.18516877, -0.68049475])

In [126]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [127]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [128]:
a5 = np.arange(1,26).reshape(5,5)

In [129]:
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [130]:
a5[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [131]:
np.sum(a5)

325

In [132]:
np.std(a5)

7.211102550927978

In [133]:
np.sum(a5[0])

15

In [134]:
np.sum(a5[1])

40

In [135]:
a =[1,2,3]

In [136]:
A = np.array(a)

In [137]:
A

array([1, 2, 3])

In [143]:
B = np.arange(5,50).reshape(5,9)
B

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [146]:
B[1:4,2:7] == 5

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [148]:
C = B[1:4,2:7]
C

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [149]:
B

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15,  5,  5,  5,  5,  5, 21, 22],
       [23, 24,  5,  5,  5,  5,  5, 30, 31],
       [32, 33,  5,  5,  5,  5,  5, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [150]:
arr = [1,2,3,4,5,6,7,8,9,10]

In [151]:
np.array(arr).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [157]:
np.random.rand(10)

array([0.81379125, 0.73360362, 0.02170032, 0.97975404, 0.09245751,
       0.78620516, 0.44183873, 0.59281043, 0.84598203, 0.32518715])

In [162]:
np.random.rand(1,15,3)

array([[[0.36351569, 0.45509681, 0.52310992],
        [0.56198081, 0.4560714 , 0.8183765 ],
        [0.88190902, 0.69943241, 0.00962057],
        [0.91729944, 0.55599717, 0.09089396],
        [0.48585127, 0.62860836, 0.86038321],
        [0.63236281, 0.568631  , 0.95524762],
        [0.71056181, 0.87890961, 0.21406248],
        [0.85002592, 0.06166569, 0.9117549 ],
        [0.87600925, 0.72854261, 0.39734167],
        [0.49665106, 0.60583585, 0.68644078],
        [0.20534692, 0.7787062 , 0.77175276],
        [0.5279238 , 0.3246713 , 0.53598762],
        [0.6295845 , 0.62988838, 0.82662119],
        [0.54512591, 0.07678482, 0.86539279],
        [0.48032056, 0.98434129, 0.23062239]]])

In [164]:
np.random.randn(1,15,3)

array([[[ 0.02006072, -0.24486954,  0.58045513],
        [-1.64721134,  0.34604886,  1.01020677],
        [ 0.01939906,  0.70847092,  0.29325711],
        [ 0.72067729,  0.83970389,  0.19854187],
        [-1.86901899,  0.61205675, -0.44219753],
        [-0.45821053,  1.64874942, -0.17145611],
        [ 0.43433747, -1.59003638,  1.13353085],
        [ 0.63753286,  0.36613195,  0.31120084],
        [-0.35521531,  0.00368838, -0.91014572],
        [ 0.21162136,  0.53102833,  0.6490087 ],
        [-0.56512806,  0.48144456, -0.61607633],
        [ 0.72766469, -0.13065241, -0.58374687],
        [ 0.43745454,  0.73717812, -0.24250882],
        [ 0.44404468,  1.34431103, -0.94338122],
        [ 0.35309473, -0.49866892,  2.22088257]]])

In [167]:
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [169]:
np.random.randint(1,20,5)

array([ 3, 10,  6,  7, 19])

In [175]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [176]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [177]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [196]:
a2 = np.ones((5,55))
a2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1

In [193]:
a1 = np.eye(10)
a1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [185]:
np.min(arr)

1

In [186]:
np.max(arr)

10

In [189]:
np.std(arr)

2.8722813232690143

In [190]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [191]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [195]:
np.exp(a1)

array([[2.71828183, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 2.71828183, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 2.71828183, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 2.71828183, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 2.71828183,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        2.71828183, 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 2.71828183, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.       

In [201]:
np.min(a2)

1.0

In [202]:
np.max(a2)

1.0

In [ ]:
np.log